### ISSUE TITLE
linux下使用方法

### ISSUE THREAD

**Issue by chenmick** [Tencent/TscanCode#10]
./TscanCode ./samples/
结果：
Start scanning, please wait...
û���ҵ�checklist.xml�����ļ��������������ļ��Ƿ����ڣ�
Parsing [cfg.ini] failed, please check whether cfg.ini exist or the format is valid.
can not find filter.ini
Checking /home/mick/code/TscanCode/samples/C#/CS_ConditionAlwaysTrue.cs...
1/15 files checked 6% done
Checking /home/mick/code/TscanCode/samples/C#/CS_ForeachInUpdate.cs...
2/15 files checked 13% done
Checking /home/mick/code/TscanCode/samples/C#/CS_StringFormat.cs...
3/15 files checked 19% done
Checking /home/mick/code/TscanCode/samples/C#/CS_UnsafeConstructor.cs...
4/15 files checked 25% done
Checking /home/mick/code/TscanCode/samples/C#/CS_dereferenceAfterNullCheck.cs...
5/15 files checked 32% done
Checking /home/mick/code/TscanCode/samples/C#/CS_dereferenceBeforeNullCheck.cs...
6/15 files checked 39% done
Checking /home/mick/code/TscanCode/samples/C#/CS_dereferenceIfNull.cs...
7/15 files checked 45% done
Checking /home/mick/code/TscanCode/samples/C++/UnintentionalOverflow.cpp...
8/15 files checked 49% done
Checking /home/mick/code/TscanCode/samples/C++/arrayIndexCheckDefect.cpp...
9/15 files checked 55% done
Checking /home/mick/code/TscanCode/samples/C++/checkNullDefect.cpp...
10/15 files checked 61% done
Checking /home/mick/code/TscanCode/samples/C++/dereferenceAfterCheck.cpp...
11/15 files checked 67% done
Checking /home/mick/code/TscanCode/samples/C++/dereferenceBeforeCheck.cpp...
12/15 files checked 74% done
Checking /home/mick/code/TscanCode/samples/C++/suspiciousSemicolon.cpp...
13/15 files checked 79% done
Checking /home/mick/code/TscanCode/samples/C++/uninitvar.cpp...
14/15 files checked 83% done
Checking /home/mick/code/TscanCode/samples/Lua/lua_LuaFuncMiss.cs...
15/15 files checked 100% done
[/home/mick/code/TscanCode/samples/C#/CS_ConditionAlwaysTrue.cs:7]: (error) (incorrectLogicOperator) Logical conjunction always evaluates to false: nLogic < 9 && nLogic > 10.
[/home/mick/code/TscanCode/samples/C++/checkNullDefect.cpp:4] -> [/home/mick/code/TscanCode/samples/C++/checkNullDefect.cpp:4]: (style) (dereferenceBeforeNullCheck) Possible null pointer dereference: npSt - otherwise it is redundant to check it against null.
[/home/mick/code/TscanCode/samples/C++/suspiciousSemicolon.cpp:4]: (portability) (suspiciousSemicolon) Suspicious use of ; at the end of 'if/for/while' statement.
[/home/mick/code/TscanCode/samples/C++/uninitvar.cpp:9]: (error) (uninitvar) uninitvar:Uninitialized variable: a

1、缺少文件cfg.ini，checklist.xml等文件。
2、window GUI下每个文件都能找出问题，linux下只识别了几个错误，请问是我的opt设置不对吗
3、使用 --xml：
报错
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 4294967295) > this->size() (which is 48)
Aborted
4、使用 --errorlist，出现段错误

小白问题比较多，谢谢

**Comment by quarkzou** [comment]
你好，感谢使用TscanCode。
目前TscanCode代码不是最新的，工具源码的更新正在公司内部的流程审批中，所以我们暂时只更新了GUI工具，预计本月底会完成源码的更新。

**Comment by chenmick** [comment]
期待你们的源码。
另外，在使用GUI时，如果文件只读，有时候错误会检测不到，希望文件读写属性不会影响到检测结果。

**Comment by chenmick** [comment]
再有，不知道我们能不能自定义一些错误检查，如果源码下来了之后

**Comment by quarkzou** [comment]
Hi chenmick, codes for TscanCode CPP version has been updated.

**Comment by chenmick** [comment]
谢谢，刚刚已经下载了，正在使用中
发自网易邮箱大师
在2017年11月30日 11:25，Quark Zou 写道： Hi chenmick, codes for TscanCode CPP version has been updated.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Tencent/TscanCode","title":"Tencent/TscanCode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Tencent/TscanCode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@quarkzou in #10: Hi chenmick, codes for TscanCode CPP version has been updated."}],"action":{"name":"View Issue","url":"https://github.com/Tencent/TscanCode/issues/10#issuecomment-348071582"}}}
