### ISSUE TITLE
如何 ignore 误报问题

### ISSUE THREAD

**Issue by kgbook** [Tencent/TscanCode#42]
相关问题： #39 

背景： 
- 非 Desktop 环境。
- tscancode 处理丢进了 git 的 pre-commit hook。

问题：
针对 TscanCode 单个误报问题（非全局），是否有类似 cpplint 的 `NOLINT` 的非全局 ignore 机制？

**Comment by ben620** [comment]
> 相关问题： #39
> 
> 背景：
> 
> * 非 Desktop 环境。
> * tscancode 处理丢进了 git 的 pre-commit hook。
> 
> 问题：
> 针对 TscanCode 单个误报问题（非全局），是否有类似 cpplint 的 `NOLINT` 的非全局 ignore 机制？

GUI有简单的误报处理能力
工具并没有集成误报跟踪的能力。误报处理涉及到不同扫描版本同一问题识别的技术，这个目前并没有开源。你可以尝试实现一些简单的实现方法

**Comment by Atient** [comment]
误报实际是以文件、函数、sub_id和web_id作为标志进行标记的，只要记录下这几个数据就可以实现自己的、可以与GUI程序通用的误报系统
我是直接用Django做了一个，实现相应的误报文件导入导出功能。
