### ISSUE TITLE
 Is C# static scanning supported?

### ISSUE THREAD

**Issue by willson-chen** [Tencent/TscanCode#44]
`For now, codes under trunk are only for TscanCode CPP version, C# and Lua version are in the internal review process. Sorry for the inconvenience.` is written in README. So I want to know if C# scan analysis is already supported.

**Comment by ben620** [comment]
> `For now, codes under trunk are only for TscanCode CPP version, C# and Lua version are in the internal review process. Sorry for the inconvenience.` is written in README. So I want to know if C# scan analysis is already supported.

Yes, the scanning tool can recognize c++, C#, and lua files automatically, if you are running the gui.exe. Otherwise, you should run the tscsharp.exe manually

**Comment by willson-chen** [comment]
Thanks :)
