### ISSUE TITLE
Linux环境web管理页面怎么弄？

### ISSUE THREAD

**Issue by flydreamhoho** [Tencent/TscanCode#59]

**Comment by Atient** [comment]
自己拿框架搭一个呗，降cli项目的运行权限重新编译一遍，用像apscheduler类似的库通过shell调工具进行扫描，然后读取输出的xml文件存到数据库里就行

至于页面就看你自己想怎么写了，嫌框架的不好用的话……

**Comment by ben620** [comment]
结果是一个人工可读的xml。可以自己写个简单的工具来实现。现在比较流行性的方式是electron

**Comment by ben620** [comment]
现在输出支持json格式了，参数加 --json。json格式更容易嵌入到html网页了
