### ISSUE TITLE
tsclua.exe 起一个新的子进程进行分析，无法获取输出报告

### ISSUE THREAD

**Issue by zhangmaijun** [Tencent/TscanCode#60]
在 Dos 窗口中，执行 tsclua.exe 命令，可以明显看到一个新的窗口打开并有分析日志及分析结果，但是分析完成后，该窗口很快消失，我们执行命令用的 Dos 窗口无任何日志输出（我使用的是 win10 操作系统）。

我尝试使用 Java ProcessBuilder 和 Python subprocess.Popen 调用 tsclua.exe 命令(tsclua.exe --xml <src>)，无法获取到任何输出信息。例如使用 Python 调用代码如下：

`# -*- encoding: UTF-8 -*-

import sys
import subprocess
import os

tscluaCommand = '%s/tsclua.exe --xml %s 2>%s' % (r'D:\development\Tencent\TscanCode', r'C:\Users\Administrator\Downloads\TscanCode-master\samples\lua', r'D:\test.xml')

p = subprocess.Popen(tscluaCommand, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

for line in p.stderr.readlines():
    print(line)
    
retval = p.wait()
if retval == 0:  
	print("tsclua run successfully.")`

1. 如果命令中，没有 2>%s 重定向，从下面的 p.stderr 里面，没有任何信息打印；
2. 如果命令中，有 2>%s 重定向，但是 重定向的文件，也是空的。

在拉起命令的时候，可以明显看到一个新的窗口，执行分析并输出结果信息。
请问如何获取到结果呢？

**Comment by Atient** [comment]
我之前试出来的结果是，目前的cmd工具都是需要管理员权限的（除了C++的扫描工具因为开源了可以降权重新编译以外），如果不是管理员权限打开的话，就会调起一个新窗口，但是输出并没从新窗口重定向回来，于是就获取不到……

总的来说，只能等lua扫描的开源了再说

**Comment by ben620** [comment]
> 在 Dos 窗口中，执行 tsclua.exe 命令，可以明显看到一个新的窗口打开并有分析日志及分析结果，但是分析完成后，该窗口很快消失，我们执行命令用的 Dos 窗口无任何日志输出（我使用的是 win10 操作系统）。
> 
> 我尝试使用 Java ProcessBuilder 和 Python subprocess.Popen 调用 tsclua.exe 命令(tsclua.exe --xml )，无法获取到任何输出信息。例如使用 Python 调用代码如下：
> 
> `# -_- encoding: UTF-8 -_-
> 
> import sys
> import subprocess
> import os
> 
> tscluaCommand = '%s/tsclua.exe --xml %s 2>%s' % (r'D:\development\Tencent\TscanCode', r'C:\Users\Administrator\Downloads\TscanCode-master\samples\lua', r'D:\test.xml')
> 
> p = subprocess.Popen(tscluaCommand, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
> 
> for line in p.stderr.readlines():
> print(line)
> 
> retval = p.wait()
> if retval == 0:
> print("tsclua run successfully.")`
> 
> 1. 如果命令中，没有 2>%s 重定向，从下面的 p.stderr 里面，没有任何信息打印；
> 2. 如果命令中，有 2>%s 重定向，但是 重定向的文件，也是空的。
> 
> 在拉起命令的时候，可以明显看到一个新的窗口，执行分析并输出结果信息。
> 请问如何获取到结果呢？

tsc的结果都打印在标准错误通道。输出结果可以用2>重定向。
完全黑的是应为工具要求管理员方式启动。

**Comment by ben620** [comment]
> 我之前试出来的结果是，目前的cmd工具都是需要管理员权限的（除了C++的扫描工具因为开源了可以降权重新编译以外），如果不是管理员权限打开的话，就会调起一个新窗口，但是输出并没从新窗口重定向回来，于是就获取不到……
> 
> 总的来说，只能等lua扫描的开源了再说

之前的编译版本需要管理员权限。现版本已经取消了。
