### ISSUE TITLE
有打算增加对Lua5.4新特性的支持吗

### ISSUE THREAD

**Issue by LuciferLau** [Tencent/TscanCode#62]
现在const定义的变量都会标记为未初始化😂

**Comment by ben620** [comment]
> 现在const定义的变量都会标记为未初始化😂

你好，已经支持了。我找机会更新下版本

**Comment by ben620** [comment]
> 现在const定义的变量都会标记为未初始化😂

新工具已经上传

**Comment by LuciferLau** [comment]
> > 现在const定义的变量都会标记为未初始化😂
> 
> 新工具已经上传

谢谢

**Comment by LuciferLau** [comment]
windows环境替换新的Lua相关文件/库后，使用默认规则扫码Lua工程出现
 _______________________________________________
|                                               
|        ( ︶︿︶)                              
|                                               
|    Oops, I am running into crash.             
|    Contact Tencent TscanCode Team please!     
|_______________________________________________
[TscLua]工具扫描失败。

**Comment by ben620** [comment]
> windows环境替换新的Lua相关文件/库后，使用默认规则扫码Lua工程出现 | Oops, I am running into crash. | Contact Tencent TscanCode Team please! [TscLua]工具扫描失败。

重新下载工具试试

**Comment by ben620** [comment]
更新了新版本，如果发现crash请重新开一个issue
