### ISSUE TITLE
global variable 

### ISSUE THREAD

**Issue by PaulAustinPA** [Tencent/TscanCode#63]
global variable 扫描缺陷，lua 代码中多处地方使用全局变量，却被检测出来建议使用local，有没有好的解决方案，避免扫描到？

**Comment by ben620** [comment]
> global variable 扫描缺陷，lua 代码中多处地方使用全局变量，却被检测出来建议使用local，有没有好的解决方案，避免扫描到？
规则是可以开关的。在cfg目录
