### ISSUE TITLE
Tscancode可以通过命令行参数或配置文件过滤多个目录和文件吗？

### ISSUE THREAD

**Issue by seshawu** [Tencent/TscanCode#68]
1.tscancode可以通过命令行参数或配置文件过滤多个目录和文件吗？如果可以，怎么写参数，怎么配？
2.tscancode能像cppcheck一样支持--suppress和-i目录或文件名 这样的参数方式吗？
3.tscancode能像cppcheck一样支持--suppression-list=suppression.txt, --suppression-=suppression.xml吗？

谢谢！

**Comment by ben620** [comment]
在配置文件里面，有个路径过滤设置
