### ISSUE TITLE
2022年4月26日更新的lua版本的配置，lua_cfg.xml 第89行格式错误

### ISSUE THREAD

**Issue by Little-Obsesity-sheep** [Tencent/TscanCode#70]
lua_cfg.xml 第89行格式错误，缺少格式</id>结尾

**Comment by Little-Obsesity-sheep** [comment]
![image](https://user-images.githubusercontent.com/36948092/166905789-8397c593-c0d8-4391-aea8-23914f2b4b1f.png)

**Comment by xiaoyuwz1234** [comment]
在lua_cfg.xml第89行后面加上 
`</id>`
