### ISSUE TITLE
Windows下怎么找不到安装文件了，现在这个lua这个不是的呀

### ISSUE THREAD

**Issue by F131514** [Tencent/TscanCode#77]
你好，现在我想在Windows下用，但是发现relase下面的windows的exe文件不可以执行是怎么回事呀

**Comment by LiAlbert** [comment]
你可以把源码clone到本地，用vs编译一个

**Comment by ben620** [comment]
历史版本
https://github.com/Tencent/TscanCode/tree/293cefdec56cdc412daac5f3f602772d8b8fe54f/release/windows
