### ISSUE TITLE
gui工具屏蔽路径中有下划线，则失效

### ISSUE THREAD

**Issue by Niteip** [Tencent/TscanCode#9]
我添加屏蔽路径，路径中有两个下划线，点添加后，发现第一个下划线没了
于是我的屏蔽规则无效了

**Comment by quarkzou** [comment]
感谢你的反馈，这个是之前版本的一个UI显示的bug，新版本已经修复了，请下载新版本使用。
![image](https://user-images.githubusercontent.com/13247564/32529538-1ca990d2-c474-11e7-8b28-31ffbb20b3a0.png)
